### ISSUE TITLE
test_io.RelatedFieldsTest.test_verbose: ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by jayvdb** [chrisdev/django-pandas#137]
I've tested this on lots of environments from Django 2.0 to 3.2, Linux and Windows, and this test fails on them all, using master.

```py
[   34s] + python3.9 runtests.py
[   35s] /home/abuild/rpmbuild/BUILD/django-pandas-0.6.4/django_pandas/tests/test_manager.py:10: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
[   35s]   import pandas.util.testing as tm
[   35s] Creating test database for alias 'default'...
[   35s] System check identified some issues:
[   35s] 
[   35s] WARNINGS:
[   35s] tests.Car: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.DataFrame: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.Dude: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.LongTimeSeries: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.MyModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.MyModelChoice: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.PivotData: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.Portfolio: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.Security: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.Spot: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.TradeLog: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.TradeLogNote: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.Trader: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.WideTimeSeries: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] tests.WideTimeSeriesDateField: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   35s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   35s] 
[   35s] System check identified 15 issues (0 silenced).
[   36s] .........E...........
[   36s] ======================================================================
[   36s] ERROR: test_verbose (django_pandas.tests.test_io.RelatedFieldsTest)
[   36s] ----------------------------------------------------------------------
[   36s] Traceback (most recent call last):
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
[   36s]     return int(value)
[   36s] ValueError: cannot convert float NaN to integer
[   36s] 
[   36s] The above exception was the direct cause of the following exception:
[   36s] 
[   36s] Traceback (most recent call last):
[   36s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.4/django_pandas/tests/test_io.py", line 153, in test_verbose
[   36s]     df = read_frame(qs, verbose=True)
[   36s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.4/django_pandas/io.py", line 136, in read_frame
[   36s]     update_with_verbose(df, fieldnames, fields)
[   36s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.4/django_pandas/utils.py", line 86, in update_with_verbose
[   36s]     df[fieldname] = function(df[fieldname])
[   36s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.4/django_pandas/utils.py", line 60, in inner
[   36s]     for obj in model.objects.filter(
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
[   36s]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
[   36s]     return self._filter_or_exclude(False, args, kwargs)
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
[   36s]     clone._filter_or_exclude_inplace(negate, args, kwargs)
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
[   36s]     self._query.add_q(Q(*args, **kwargs))
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
[   36s]     clause, _ = self._add_q(q_object, self.used_aliases)
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
[   36s]     child_clause, needed_inner = self.build_filter(
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
[   36s]     condition = self.build_lookup(lookups, col, value)
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
[   36s]     lookup = lookup_class(lhs, rhs)
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
[   36s]     self.rhs = self.get_prep_lookup()
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/lookups.py", line 240, in get_prep_lookup
[   36s]     rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
[   36s]   File "/usr/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
[   36s]     raise e.__class__(
[   36s] ValueError: Field 'id' expected a number but got nan.
```

**Comment by chrisdev** [comment]
Hi. 
Just back from some time off. Looks like we have to do some rewriting for Python 3.9??

**Comment by jayvdb** [comment]
This also occurred on Python 3.7

**Comment by mcepl** [comment]
And 3.8.:
```
[   40s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-django-pandas-0.6.2-0.x86_64/usr/lib/python3.8/site-packages
[   40s] + python3.8 runtests.py
[   41s] /home/abuild/rpmbuild/BUILD/django-pandas-0.6.2/django_pandas/tests/test_manager.py:10: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
[   41s]   import pandas.util.testing as tm
[   41s] Creating test database for alias 'default'...
[   41s] System check identified some issues:
[   41s]
[   41s] WARNINGS:
[   41s] tests.Car: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.DataFrame: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.Dude: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.LongTimeSeries: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.MyModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.MyModelChoice: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.PivotData: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.Portfolio: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.Security: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.Spot: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.TradeLog: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.TradeLogNote: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.Trader: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.WideTimeSeries: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s] tests.WideTimeSeriesDateField: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
[   41s] 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
[   41s]
[   41s] System check identified 15 issues (0 silenced).
[   41s] ........E...........
[   41s] ======================================================================
[   41s] ERROR: test_verbose (django_pandas.tests.test_io.RelatedFieldsTest)
[   41s] ----------------------------------------------------------------------
[   41s] Traceback (most recent call last):
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
[   41s]     return int(value)
[   41s] ValueError: cannot convert float NaN to integer
[   41s]
[   41s] The above exception was the direct cause of the following exception:
[   41s]
[   41s] Traceback (most recent call last):
[   41s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.2/django_pandas/tests/test_io.py", line 143, in test_verbose
[   41s]     df = read_frame(qs, verbose=True)
[   41s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.2/django_pandas/io.py", line 128, in read_frame
[   41s]     update_with_verbose(df, fieldnames, fields)
[   41s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.2/django_pandas/utils.py", line 83, in update_with_verbose
[   41s]     df[fieldname] = function(df[fieldname])
[   41s]   File "/home/abuild/rpmbuild/BUILD/django-pandas-0.6.2/django_pandas/utils.py", line 57, in inner
[   41s]     for obj in model.objects.filter(
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
[   41s]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
[   41s]     return self._filter_or_exclude(False, args, kwargs)
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
[   41s]     clone._filter_or_exclude_inplace(negate, args, kwargs)
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
[   41s]     self._query.add_q(Q(*args, **kwargs))
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1393, in add_q
[   41s]     clause, _ = self._add_q(q_object, self.used_aliases)
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
[   41s]     child_clause, needed_inner = self.build_filter(
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
[   41s]     condition = self.build_lookup(lookups, col, value)
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
[   41s]     lookup = lookup_class(lhs, rhs)
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
[   41s]     self.rhs = self.get_prep_lookup()
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/lookups.py", line 240, in get_prep_lookup
[   41s]     rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
[   41s]   File "/usr/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
[   41s]     raise e.__class__(
[   41s] ValueError: Field 'id' expected a number but got nan.
[   41s]
[   41s] ----------------------------------------------------------------------
[   41s] Ran 20 tests in 0.502s
[   41s]
[   41s] FAILED (errors=1)
```
