### ISSUE TITLE
UnicodeDecodeError when installing django-pandas with pip3 in Docker

### ISSUE THREAD

**Issue by utapyngo** [chrisdev/django-pandas#90]
```
build	25-Jan-2018 09:47:12	Collecting django-pandas==0.5.0 (from -r /tmp/requirements.txt (line 40))
build	25-Jan-2018 09:47:12	  Downloading django-pandas-0.5.0.tar.gz
build	25-Jan-2018 09:47:12	    Complete output from command python setup.py egg_info:
build	25-Jan-2018 09:47:12	    Traceback (most recent call last):
build	25-Jan-2018 09:47:12	      File "<string>", line 1, in <module>
build	25-Jan-2018 09:47:12	      File "/tmp/pip-build-_xb4994q/django-pandas/setup.py", line 5, in <module>
build	25-Jan-2018 09:47:12	        open('README.rst').read() + '\n\n' +
build	25-Jan-2018 09:47:12	      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
build	25-Jan-2018 09:47:12	        return codecs.ascii_decode(input, self.errors)[0]
build	25-Jan-2018 09:47:12	    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1046: ordinal not in range(128)
```

This is caused by line "Hélio Meira Lins" in README.rst.

Similar issues in other projects:
- https://github.com/crsmithdev/arrow/issues/208
- https://github.com/keleshev/schema/issues/68

Here is how to fix it by using `codecs.open()` instead of plain `open()`:
- https://github.com/keleshev/schema/pull/69/files#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by meiralins** [comment]
lol

**Comment by chrisdev** [comment]
@meiralins your name is a killing word...You must conquer the worm ... conquer Shai-Hulud...conquer Dune 😃

**Comment by chrisdev** [comment]
@utapyngo you want to send a PR

**Comment by utapyngo** [comment]
I'm not sure I won't break Python 2.7 compatibility.
